[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
skillchain = "SkiLLcHaiNPRoGraM11111111111111111111111111"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
